# generic
z_offset_scale: 1.5
visualize: true
# node
marker_scale: 0.4
marker_alpha: 1.0
use_sphere_marker: false
use_label: false
label_height: 0.5
label_scale: 0.25
use_bounding_box: false
bounding_box_alpha: 0.3
# edge
use_edge_source: true
interlayer_edge_scale: 0.05
interlayer_edge_alpha: 0.3
interlayer_edge_use_color: false
interlayer_edge_insertion_skip: 10
intralayer_edge_scale: 0.03
intralayer_edge_alpha: 0.6
intralayer_edge_use_color: false
intralayer_edge_insertion_skip: 0
