dynamic_semantic_labels: [20]
structure_labels: [0, 2, 3, 4, 8, 9, 12, 13, 15, 17, 19]
object_labels: [5, 7, 10, 11, 14, 16, 18]
stuff_labels: [0, 1, 2, 3, 4, 6, 8, 9, 12, 13, 15, 17, 19]
walls_labels: [12, 19]
floor_labels: [3, 15]
