dynamic_semantic_labels: [20]
structure_labels: [0, 11, 14, 19]
object_labels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19]
stuff_labels: [0, 11, 14, 19]
walls_labels: [12]
floor_labels: [7]