%YAML:1.0

################################################################################
# Created by: YC                                                               #
# Created on: 2021-11-15T09:11:52.289804                                       #
################################################################################

# General sensor definitions
camera_id: left_cam

# Sensor extrinsics wrt. the body-frame
T_BS:
  cols: 4
  rows: 4
  data: [1.0, 0.0, 0.0, 0.0,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]

  #data:  [-0.00068716,  0.00584728,  0.99998267,  0.01013482,
          #-0.35553921, -0.93464679,  0.00522092,  0.05753265,
           #0.93466112, -0.35552946,  0.00272119, -0.10924056,
           #0.00000000,  0.00000000,  0.00000000,  1.00000000]

# Camera specific definitions
rate_hz: 30
resolution: [1280, 720]  # [width, height]
camera_model: pinhole
intrinsics: [631.47875965626, 630.9535522460938, 640.2518310546875, 365.23785400390625]  # [fu, fv, cu, cv]
distortion_model: radtan
distortion_coefficients: [0.0, 0.0, 0.0, 0.0]  # model dependent
